=== bencoz/EnigmaMachineJava/EnigmaEx/EnigmaMachineFactory/src/resources/Enigma.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2008 rel. 2 (http://www.altova.com) by mazuki (darksiderg) -->
<!--W3C Schema generated by XMLSpy v2008 rel. 2 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Rotors">
		<xs:complexType>
			<xs:sequence maxOccurs="unbounded">
				<xs:element ref="Rotor"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Rotor">
		<xs:complexType>
			<xs:sequence maxOccurs="unbounded">
				<xs:element ref="Mapping"/>
			</xs:sequence>
			<xs:attribute name="notch" type="xs:int" use="required"/>
			<xs:attribute name="id" type="xs:int" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Reflectors">
		<xs:complexType>
			<xs:sequence maxOccurs="5">
				<xs:element ref="Reflector"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Reflector">
		<xs:complexType>
			<xs:sequence maxOccurs="unbounded">
				<xs:element ref="Reflect"/>
			</xs:sequence>
			<xs:attribute name="id" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="I"/>
						<xs:enumeration value="II"/>
						<xs:enumeration value="III"/>
						<xs:enumeration value="IV"/>
						<xs:enumeration value="V"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="Reflect">
		<xs:complexType>
			<xs:attribute name="input" type="xs:int" use="required"/>
			<xs:attribute name="output" type="xs:int" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Mapping">
		<xs:complexType>
			<xs:attribute name="left" type="xs:string" use="required"/>
			<xs:attribute name="right" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Machine">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ABC" type="xs:string"/>
				<xs:element ref="Rotors"/>
				<xs:element ref="Reflectors"/>
			</xs:sequence>
			<xs:attribute name="rotors-count" type="xs:int" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Enigma">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Machine"/>
				<xs:element ref="Decipher" minOccurs="0"/>
				<xs:element ref="Battlefield" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Dictionary">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Words" type="xs:string"/>
			</xs:sequence>
			<xs:attribute name="exclude-chars" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Decipher">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Dictionary"/>
			</xs:sequence>
			<xs:attribute name="agents" type="xs:int" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Battlefield">
		<xs:complexType>
			<xs:attribute name="rounds" type="xs:int" use="required"/>
			<xs:attribute name="level" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="Easy"/>
						<xs:enumeration value="Medium"/>
						<xs:enumeration value="Hard"/>
						<xs:enumeration value="Insane"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="battle-name" type="xs:string" use="required"/>
			<xs:attribute name="allies" type="xs:int" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== bencoz/EnigmaMachineJava/EnigmaEx/EnigmaMachineFactory/src/resources/ex1-sanity-small.xml
<?xml version="1.0" encoding="UTF-8"?>
<Enigma xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Enigma.xsd">
	<Machine rotors-count="2">
		<ABC>
			ABCDEF
		</ABC>
		<Rotors>
			<Rotor id="1" notch="4">
				<Mapping right="A" left="F"/>
				<Mapping right="B" left="E"/>
				<Mapping right="C" left="D"/>
				<Mapping right="D" left="C"/>
				<Mapping right="E" left="B"/>				
				<Mapping right="F" left="A"/>				
			</Rotor>
			<Rotor id="3" notch="6">
				<Mapping right="A" left="B"/>
				<Mapping right="B" left="A"/>
				<Mapping right="C" left="D"/>
				<Mapping right="D" left="C"/>
				<Mapping right="E" left="F"/>				
				<Mapping right="F" left="E"/>				
			</Rotor>						
			<Rotor id="2" notch="1">
				<Mapping right="A" left="E"/>
				<Mapping right="B" left="B"/>
				<Mapping right="C" left="D"/>
				<Mapping right="D" left="F"/>
				<Mapping right="E" left="C"/>				
				<Mapping right="F" left="A"/>				
			</Rotor>						
		</Rotors>
		<Reflectors>
			<Reflector id="I">
				<Reflect input="1" output="4"/>
				<Reflect input="2" output="5"/>
				<Reflect input="3" output="6"/>								
			</Reflector>
			<Reflector id="II">
				<Reflect input="1" output="2"/>
				<Reflect input="3" output="4"/>
				<Reflect input="5" output="6"/>
			</Reflector>			
		</Reflectors>
	</Machine>	
</Enigma>

=== bencoz/EnigmaMachineJava/EnigmaEx/EnigmaMachineFactory/src/resources/ex1-sanity-paper-enigma.xml
<?xml version="1.0" encoding="UTF-8"?>
<Enigma xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Enigma.xsd">
	<Machine rotors-count="3">
		<ABC>
			ABCDEFGHIJKLMNOPQRSTUVWXYZ
		</ABC>
		<Rotors>
			<Rotor id="1" notch="17">
				<Mapping right="E" left="A"/>
				<Mapping right="K" left="B"/>
				<Mapping right="M" left="C"/>
				<Mapping right="F" left="D"/>
				<Mapping right="L" left="E"/>
				<Mapping right="G" left="F"/>
				<Mapping right="D" left="G"/>
				<Mapping right="Q" left="H"/>
				<Mapping right="V" left="I"/>
				<Mapping right="Z" left="J"/>
				<Mapping right="N" left="K"/>
				<Mapping right="T" left="L"/>
				<Mapping right="O" left="M"/>
				<Mapping right="W" left="N"/>
				<Mapping right="Y" left="O"/>
				<Mapping right="H" left="P"/>
				<Mapping right="X" left="Q"/>
				<Mapping right="U" left="R"/>
				<Mapping right="S" left="S"/>
				<Mapping right="P" left="T"/>
				<Mapping right="A" left="U"/>
				<Mapping right="I" left="V"/>
				<Mapping right="B" left="W"/>
				<Mapping right="R" left="X"/>
				<Mapping right="C" left="Y"/>
				<Mapping right="J" left="Z"/>
			</Rotor>
			<Rotor id="2" notch="5">
				<Mapping right="A" left="A"/>
				<Mapping right="J" left="B"/>
				<Mapping right="D" left="C"/>
				<Mapping right="K" left="D"/>
				<Mapping right="S" left="E"/>
				<Mapping right="I" left="F"/>
				<Mapping right="R" left="G"/>
				<Mapping right="U" left="H"/>
				<Mapping right="X" left="I"/>
				<Mapping right="B" left="J"/>
				<Mapping right="L" left="K"/>
				<Mapping right="H" left="L"/>
				<Mapping right="W" left="M"/>
				<Mapping right="T" left="N"/>
				<Mapping right="M" left="O"/>
				<Mapping right="C" left="P"/>
				<Mapping right="Q" left="Q"/>
				<Mapping right="G" left="R"/>
				<Mapping right="Z" left="S"/>
				<Mapping right="N" left="T"/>
				<Mapping right="P" left="U"/>
				<Mapping right="Y" left="V"/>
				<Mapping right="F" left="W"/>
				<Mapping right="V" left="X"/>
				<Mapping right="O" left="Y"/>
				<Mapping right="E" left="Z"/>
			</Rotor>
			<Rotor id="3" notch="22">
				<Mapping right="B" left="A"/>
				<Mapping right="D" left="B"/>
				<Mapping right="F" left="C"/>
				<Mapping right="H" left="D"/>
				<Mapping right="J" left="E"/>
				<Mapping right="L" left="F"/>
				<Mapping right="C" left="G"/>
				<Mapping right="P" left="H"/>
				<Mapping right="R" left="I"/>
				<Mapping right="T" left="J"/>
				<Mapping right="X" left="K"/>
				<Mapping right="V" left="L"/>
				<Mapping right="Z" left="M"/>
				<Mapping right="N" left="N"/>
				<Mapping right="Y" left="O"/>
				<Mapping right="E" left="P"/>
				<Mapping right="I" left="Q"/>
				<Mapping right="W" left="R"/>
				<Mapping right="G" left="S"/>
				<Mapping right="A" left="T"/>
				<Mapping right="K" left="U"/>
				<Mapping right="M" left="V"/>
				<Mapping right="U" left="W"/>
				<Mapping right="S" left="X"/>
				<Mapping right="Q" left="Y"/>
				<Mapping right="O" left="Z"/>
			</Rotor>
		</Rotors>
		<Reflectors>
			<Reflector id="I">
				<Reflect input="1" output="25"/>
				<Reflect input="2" output="18"/>
				<Reflect input="3" output="21"/>
				<Reflect input="4" output="8"/>
				<Reflect input="5" output="17"/>
				<Reflect input="6" output="19"/>
				<Reflect input="7" output="12"/>
				<Reflect input="9" output="16"/>
				<Reflect input="10" output="24"/>
				<Reflect input="11" output="14"/>
				<Reflect input="13" output="15"/>
				<Reflect input="20" output="26"/>
				<Reflect input="22" output="23"/>
			</Reflector>
		</Reflectors>
	</Machine>	
</Enigma>
